default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_uuid_development

test:
  <<: *default
  database: rails_uuid_test

production:
  <<: *default
  database: rails_uuid_production
  username: rails_uuid
  password: <%= ENV['RAILS_UUID_DATABASE_PASSWORD'] %>
